### PR TITLE
Implemented boosting for the unique traits in collection

### PR DESCRIPTION
**Pull request by impreso**
# Summary
* Implemented ranking boosting mechanism for unique traits (when trait_count == 1 , we boost  Information Content by constant factor 2)

# Tests
* Added new test
* Run scoring for collections  and confirmed the fix.

### CODE REVIEW

**Comment by aschlosberg** [comment]
Doubling the rarity ranking of 1/n pieces is arbitrary and goes against the principles of being grounded in mathematical reasoning. I'm not in favour of this.

**Comment by cxkoda** [comment]
Sorry I'm probably not in the loop about the issue that is being addressed here. Could you please summarize it and explain your reasoning behind your change? 

> boost Information Content by constant factor 2
I agree with @aschlosberg on this. The information content is a well defined quantity. Arbitrarily multiplying it with something changes it's meaning which would invalidate the information theoretical grounding of the approach.

**Review by aschlosberg — CHANGES_REQUESTED** [review]
Just adding my original comment as an actual review so it's blocking:

> Doubling the rarity ranking of 1/n pieces is arbitrary and goes against the principles of being grounded in mathematical reasoning. I'm not in favour of this.

**Comment by theelderbeever** [comment]
Does changing the base of the log help to push rare things to higher information?

**Comment by impreso** [comment]
Decided to postpone this , as we debating in the group what's the best way to address the desired properties in the scoring formula.

**Comment by aschlosberg** [comment]
> Does changing the base of the log help to push rare things to higher information?

Nah it will only scale everything by a constant factor.

**Pull request closed without merging**
